# Generated by Django 3.1.4 on 2020-12-26 09:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('IOU_APP1', '0004_auto_20201226_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_iou',
            name='IOU_json',
            field=jsonfield.fields.JSONField(default={'balance': '', 'name': 'Ankit', 'owed_by': {}, 'owes': {}}),
        ),
    ]
